### ISSUE TITLE
Postgrey (Postfix Greylisting)

### ISSUE THREAD

**Issue by medevul** [mikaku/Monitorix#102]
Needs support for a commonly used greylisting feature found with Postfix. Information on Postgrey can be found at it's home page, http://postgrey.schweikert.ch/

evul

**Comment by mikaku** [comment]
Hi,

Since I don't know anything about this tool, I need to know how different it is from the `milter-greylist` tool currently supported by Monitorix.

So, what are the statistical values offered by this Greylisting tool?
Thanks.

**Comment by bluegroper** [comment]
<subscribed>

**Comment by bluegroper** [comment]
Lets see whether I can be of any assistance, rather than just a nuisance.
It would be superb if Monitorix could include Greylisting graph for CentOS server/s running postfix with postgrey package.  Its a common configuration.
I believe greylisting data is needed from some logs.
In Monitorix 3.8.1 greylisting stats were included as Rejected (Red) messages in graphs, but this no longer happens in version 3.9.
Where did that greylisting data come from in 3.8.1 ?  
What command collected the data ?  Is it useful ?
Should we be trying to find some clean data using pflogsumm ?
How to progress ??

**Comment by mikaku** [comment]
@bluegroper,

> In Monitorix 3.8.1 greylisting stats were included as Rejected (Red) messages in graphs, but this no longer happens in version 3.9.

The only change in the `mail_update()` function was to include support for a new value. This https://github.com/mikaku/Monitorix/commit/4ce6404a3e129258c2c52966e684e0c80640f97d from #118 is commit that did the change. (perhaps I misunderstood your private email, sorry).

>  Where did that greylisting data come from in 3.8.1 ?

Greylisting data in Postfix was never supported, unless you specifically added the greylisting values in some part of `pflogsumm`. Currently the only Greylisting software is `milter-greylist`.

>  How to progress this ticket ??

Just install Postgrey in your server, let it run for a while and check its logfile to see Greylisting results. If they are consistent then paste it here in.

**Comment by bluegroper** [comment]
Hey Jordi

I'm detecting some confusion.
We've been using postgrey for years. More recently we start using monitorix.
Somehow, the code in Monitorix 3.8.1 was including data for greylisted
emails as Rejected (Red) in our graphs.
This no longer happens in 3.9.
Sorry, I haven't had time to try and understand your code, or diff any
changes.
Maybe caused by the word "rejected" included in every greylisting line in
logs ? (See below)
I better check to see whether any other CentOS packages were updated around
same time as Monitorix.
Possibly another updated package is indirectly causing this changed graph
appearance.  Random idea.

Perhaps all the points above are irrelevant, and we should simply
concentrate on getting greylisting working as intended by *you*.
Small clip below from recent maillog showing plenty of greylistings.
What next steps needed to turn these loglines into usable greylisting data
for monitorix ?

Also, I need to check underlying monitorix data.  Looks suspiciously like
Delivered (Dark Blue) emails are NOT being included in main email graph.
Wonder whether these issues are related ?

Cheers

Nov 13 04:17:21 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <ail@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
ail@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:22 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=avidj@joco.com.au
Nov 13 04:17:22 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <avidj@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
avidj@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:22 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=clagel@joco.com.au
Nov 13 04:17:22 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <clagel@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
clagel@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:23 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=davidj@joco.com.au
Nov 13 04:17:23 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <davidj@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
davidj@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:23 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=it-buyer@joco.com.au
Nov 13 04:17:23 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <it-buyer@joco.com.au>: Recipient
address rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us>
to=<it-buyer@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:24 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=johnson@joco.com.au
Nov 13 04:17:24 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <johnson@joco.com.au>: Recipient
address rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us>
to=<johnson@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:24 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=mail@joco.com.au
Nov 13 04:17:24 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <mail@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
mail@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:25 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=oclagel@joco.com.au
Nov 13 04:17:25 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <oclagel@joco.com.au>: Recipient
address rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us>
to=<oclagel@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:25 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=ohnsmithsvt@joco.com.au
Nov 13 04:17:25 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <ohnsmithsvt@joco.com.au>: Recipient
address rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us>
to=<ohnsmithsvt@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net
>
Nov 13 04:17:26 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=t-buyer@joco.com.au
Nov 13 04:17:26 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <t-buyer@joco.com.au>: Recipient
address rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us>
to=<t-buyer@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:26 centos7 postgrey[850]: action=greylist, reason=new,
client_name=unknown, client_address=216.241.193.224, sender=
rpqnii@djj.state.fl.us, recipient=vidj@joco.com.au
Nov 13 04:17:26 centos7 postfix/smtpd[5765]: NOQUEUE: reject: RCPT from
unknown[216.241.193.224]: 450 4.2.0 <vidj@joco.com.au>: Recipient address
rejected: Greylisted for 240 seconds; from=<rpqnii@djj.state.fl.us> to=<
vidj@joco.com.au> proto=SMTP helo=<216-241-193-224.scinternet.net>
Nov 13 04:17:29 centos7 postfix/smtpd[5765]: disconnect from
unknown[216.241.193.224]

**Comment by mikaku** [comment]
Please, don't use email replies as they don't support Markdown formatting. Take some time to learn how Markdown works.

**Comment by bluegroper** [comment]
Illegible clip from logfile deleted.  Agree completely.  It looked fine in email, but pointless in this place.  Note to self, and sorry for bother.

Yes, postgrey does the greylisting, and makes some logfiles.
I was assuming (perhaps incorrectly) that monitorix would somehow gather the data, and make useful statistics.
When time permits, I'll see if I can find any summary from postgrey or pflogsumm.

**Comment by mikaku** [comment]
>  When time permits, I'll see if I can find any summary from postgrey or pflogsumm.

I'm sure that Postgrey shows statistics in some file or whatever, so please, let me know when you discover it. I'll be glad to include support for Postgrey.

Thanks.

**Comment by bluegroper** [comment]
**pflogsumm**

Here's some sample output from pflogsumm from a very small mailserver.
Observations :
1.  No _greylisting_ stats from pflogsumm ?
2.  Looks suspiciously like greylisted emails being incorrectly (?) included in "rejected" counters.
```
# pflogsumm -d yesterday /var/log/maillog

Postfix log summaries for Nov 18

Grand Totals
------------
messages

     55   received
     59   delivered
      0   forwarded
      0   deferred
      0   bounced
    511   rejected (89%)
      0   reject warnings
      0   held
      0   discarded (0%)

  32881k  bytes received
  32902k  bytes delivered
     25   senders
     24   sending hosts/domains
     21   recipients
     14   recipient hosts/domains


Per-Hour Traffic Summary
------------------------
    time          received  delivered   deferred    bounced     rejected
    --------------------------------------------------------------------
    0000-0100           1          1          0          0         18 
    0100-0200           0          0          0          0         28 
    0200-0300           0          0          0          0          2 
    0300-0400           1          1          0          0          2 
    0400-0500           1          1          0          0         36 
    0500-0600           0          0          0          0         14 
    0600-0700           0          0          0          0         13 
    0700-0800           1          1          0          0         27 
    0800-0900           4          4          0          0         17 
    0900-1000           5          5          0          0         13 
    1000-1100           3          3          0          0         19 
    1100-1200           1          1          0          0         27 
    1200-1300           6          6          0          0         22 
    1300-1400           5          6          0          0         32 
    1400-1500           3          3          0          0         16 
    1500-1600           2          2          0          0         35 
    1600-1700           7          8          0          0         20 
    1700-1800           2          2          0          0         40 
    1800-1900           2          2          0          0          9 
    1900-2000           1          1          0          0         33 
    2000-2100           2          2          0          0          5 
    2100-2200           5          6          0          0         21 
    2200-2300           2          3          0          0         11 
    2300-2400           1          1          0          0         51 

```
**postgreyreport**

https://wiki.centos.org/HowTos/postgrey#head-70ed10e62fb7da94deb39a987e1e4e205c2ae2c5
postgreyreport seems to only make a big list all the relevant greylisting triplets without giving any statistics.

Running out of ideas.
Seems there's no already existing way of collecting useful statistics from postgrey.

**Comment by bluegroper** [comment]
??
https://www.fi.muni.cz/~kas/blog/index.cgi/computers/postgrey-statistics.html

**Comment by mikaku** [comment]
JFYI, I'm working on introducing support of `postgrey` based on some logs sent by a user vial email.

**Comment by mikaku** [comment]
The Postgrey support reads the `mail_log` file and searches for a specific type of lines. It works as following:

Lines of type **action=greylist, reason=new** and **action=greylist, reason=early-retry** are treated together and appear as *Greylisted* in the graph. The following is an example of this type of lines:

```
Jun 19 14:57:28 web01 postgrey[1143]: action=greylist, reason=new, client_name=sender-server, client_address=1.2.3.4, sender= x@x.x, recipient=y@y.y
Jun 19 15:01:50 web01 postgrey[1143]: action=greylist, reason=early-retry (38s missing), client_name= sender-server, client_address=1.2.3.4, sender= x@x.x, recipient= y@y.y
```

Lines of type **action=pass, reason=triplet found** appear as *Passed* in the graph. The following is an example of this type of lines:

```
Jun 19 15:12:50 web01 postgrey[1143]: action=pass, reason=triplet found, delay=386, client_name= sender-server, client_address=1.2.3.4, sender= x@x.x, recipient= y@y.y
```

and finally, lines of type **action=pass, reason=client whitelist** appear as *Whitelisted* in the graph. The following is an example of this type of lines:

```
Jun 19 15:03:26 web01 postgrey[1143]: action=pass, reason=client whitelist, client_name= sender-server, client_address=1.2.3.4, sender= x@x.x, recipient= y@y.y
```

The following is an example of how all this will be represented in the Greylisting graph:
![test-postgrey](https://user-images.githubusercontent.com/829885/27326877-0b8ace28-55ad-11e7-88f6-720e4ea4bc20.png)

**Comment by mikaku** [comment]
@bluegroper, can't you compare these log lines with yours? I don't remember if your logfile was already offering the same Postgrey stats.

Thanks.
