### ISSUE TITLE
ERROR: while updating /var/lib/monitorix/system.rrd

### ISSUE THREAD

**Issue by morfikov** [mikaku/Monitorix#107]
Something's wrong with the system graph module. The following is what I get after starting monitorix:

	Thu Sep  3 10:49:19 2015 - Starting Monitorix version 3.7.0 (pid 119663).
	Thu Sep  3 10:49:19 2015 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
	Thu Sep  3 10:49:19 2015 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
	Thu Sep  3 10:49:19 2015 - Initializing graphs.
	Thu Sep  3 10:49:19 2015 - Generating the 'index.html' file.
	Thu Sep  3 10:49:19 2015 - Started built-in HTTP server (pid 119697).
	Thu Sep  3 10:49:19 2015 - Ok, ready.
	HTTPServer: You can connect to your server at http://localhost:8080/
	Thu Sep  3 10:51:00 2015 - ERROR: while updating /var/lib/monitorix/system.rrd: /var/lib/monitorix/system.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '' to float
	Thu Sep  3 10:53:00 2015 - ERROR: while updating /var/lib/monitorix/system.rrd: /var/lib/monitorix/system.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '' to float

Every other module works fine, just the system one fails all the time.

**Comment by mikaku** [comment]
@morfikov,

Yes, there was a bad initialization in a pair of values not accepted by the new RRDtool 1.5 version. This has been already fixed in the current development version (issue #91).

To know all the changes made in the current development version, just check the Changes file <https://github.com/mikaku/Monitorix/blob/master/Changes>.

Thanks anyway for your feedback.
Regards.
