### ISSUE TITLE
Directory Usage - filecount

### ISSUE THREAD

**Issue by mmattel** [mikaku/Monitorix#112]
It would be great to have the ability to add to a directory to be monitored not only the directory size but also the number of files.

Usecase: when you eg monitor a /tmp or a up/download directory, it is not only useful to know what the current used size is, but also how many files are currently present.

**Comment by mmattel** [comment]
Forgot to mention, as parameter to a directory of course...

**Comment by mikaku** [comment]
You meant the number of files in the directory only, or also in all its subdirectories?
(The later will be more aggressive, of course)

I think I could introduce a way to be able to differentiate how the directories will be monitored: monitoring their size or their files. Something like this:

```
<du>
        list = System, Users
        <desc>
                0 = /var/spool/mail, /var/spool/mqueue, /etc, /var/ftp, /tmp
                1 = /home/ace, /home/gene, /home/paul, /home/peter
        </desc>
        <type>
                0 = size
                1 = files
        </type>
        <dirmap>
                /var/spool/mail = Mail boxes
                /var/spool/mqueue = Mail queue
        </dirmap>
        graphs_per_row = 2
        rigid = 0
        limit = 100
</du>
```

It's not possible to mix different types inside a directory group because the graph would not scale correctly.

**Comment by mmattel** [comment]
👍

**Comment by mikaku** [comment]
Please, test the last commit and let me know how it works.
