### ISSUE TITLE
Process statistic not displaying network usage for some processes

### ISSUE THREAD

**Issue by skibbipl** [mikaku/Monitorix#117]
I've configured process statistic like this:
```
<process>
        <list>
                0 = httpd, sshd, ntpd, mysqld, postgres, nmbd, smbd
                1 = clamd, dovecot, imap
        </list>
        <desc>
                dovecot = Dovecot
                httpd = Apache
                imap = Postfix
                mysqld = MySQL
                postgres = PostgreSQL
        </desc>
        rigid = 2, 0, 0, 0, 0, 0, 0, 0
        limit = 100, 1000, 1000, 1000, 1000, 1000, 1000, 1000
</process>
```
But I'm getting empty graph for services in list 0:
![process04z 1day](https://cloud.githubusercontent.com/assets/4746858/10308320/39a04e5e-6c35-11e5-8bef-123cb23bed8a.png)

There are no errors in monitorix log. I'm using debian unstable. At least postgres should generate some network traffic, as it is configured as destination server for database replication.

**Comment by IzzySoft** [comment]
Chiming in: on one of my machines, Monitorix seems unable to detect the apache2 process data in this segment (while the dedicated Apache stats show up fine). Also no errors in the logs. I doubt Apache is using no memory at all (all values there show "0" for Apache – while sshd, ntpd, MySQL and clamd show reasonable values). Apache shows "0" for ***all*** process stats, as if it wouldn't be running (which clearly contradicts the Apache stats).

I've checked the config against `ps` output: the latter shows Apache as `/usr/sbin/apache2`, my config has it as `apache2` – right as it is on my other machines, where Apache shows up fine, eating quite a lot of memory on some.

Funny thing: `amavis` seems not to be picked up either (configured as `amavisd-new`):

~~~
amavis   23347  0.0  6.0  74172 60144 ?        Ss   Oct03   0:24 /usr/sbin/amavisd-new (master)
amavis   23367  0.0  6.1  84520 61476 ?        S    Oct03   0:03 /usr/sbin/amavisd-new (ch2-avail)
amavis   23368  0.0  6.7  90452 67280 ?        S    Oct03   0:05 /usr/sbin/amavisd-new (ch2-avail)
~~~

Is Monitorix having trouble with processes which start with an `a` here? These two are the only ones showing "0" everywhere (even for number of processes, which cannot be true). It cannot be the path, as `sshd` picks up fine for `/usr/sbin/sshd`. Neither the CLI parameter can be the cause, as `ntpd` picks up fine for `/usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:103`.

Hints for debugging welcome to shed some light, if possible :)

----

Side-question is how I could integrate postfix here, which seems to run with a bunch of different processes using different names:

~~~
ps aux |grep postfix
root      3483  0.0  0.1   4980  1728 ?        Ss   Oct02   0:05 /usr/lib/postfix/master
postfix   3491  0.0  0.1   5156  1784 ?        S    Oct02   0:01 qmgr -l -t fifo -u
postfix   9578  0.0  0.1   5024  1672 ?        S    13:42   0:00 pickup -l -t fifo -u -c -o content_filter= -o receive_override_options=no_header_body_checks
postfix   9880  0.0  0.1   5024  1676 ?        S    13:48   0:00 showq -t unix -u -c
postfix  23356  0.0  0.2   5440  2256 ?        S    Oct03   0:00 tlsmgr -l -t unix -u -c
~~~

And what `dovecot` put into my Monitorix config will pickup here:

~~~
root      3127  0.0  0.0   2556   792 ?        Ss   Oct02   0:01 /usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
dovecot   3129  0.0  0.0   2104   776 ?        S    Oct02   0:00 dovecot/anvil
root      3130  0.0  0.0   2236   936 ?        S    Oct02   0:00 dovecot/log
~~~

(obviously only the first one, as the stats show 1 process only. So how to have Monitorix picking up the other two as well? Using a wildcard, maybe, e.g. `dovecot*`?)

**Comment by mikaku** [comment]
Monitorix uses the command `ps -eo pid,comm,command` to detect the PID of the process name you defined in the `<list>` block.

@skibbipl,

Please, make sure that the names you defined in `list 0` match with the real names of the process you are trying to monitor. Also, once you know the PID of one of these processes, please, pastebin the contents of the file `/proc/<PID>/io`, just to make sure it has supported values.

Finally, please, paste the kernel version you are using.


@IzzySoft,

Make sure (using the command supplied above) that the process name is really `apache2`, sometimes is also called as `httpd`. Same with `amavis`.

> Is Monitorix having trouble with processes which start with an a here?

Heh, well, after checking in all my servers ... I realized that I don't have any process starting with `a` so ... I can't say.

> Side-question is how I could integrate postfix here, which seems to run with a bunch of different processes using different names:

Use the right arguments in `ps`. See above.

> And what dovecot put into my Monitorix config will pickup here:

Same as above.

**Comment by IzzySoft** [comment]
For Apache it works with the very same configuration on my other servers (Debian Wheezy and Ubuntu 12.04 – the one not working is on Bananian, which is based on Wheezy).

> Make sure (using the command supplied above) that the process name is really apache2, sometimes is also called as httpd. Same with amavis.

I did so, see my post again: "configured as `amavisd-new`".

~~~
ps -eo pid,comm,command|grep amavis
21316 grep            grep amavis
23347 /usr/sbin/amavi /usr/sbin/amavisd-new (master)
23367 /usr/sbin/amavi /usr/sbin/amavisd-new (ch2-avail)
23368 /usr/sbin/amavi /usr/sbin/amavisd-new (ch2-avail)
~~~

Makes 3 processes – Monitorix lists 0 processes, 0 threads. Apache: "my config has it as `apache2`"

~~~
ps -eo pid,comm,command|grep apache2
 1848 /usr/sbin/apach /usr/sbin/apache2 -k start
21404 grep            grep apache2
22593 /usr/sbin/apach /usr/sbin/apache2 -k start
22594 /usr/sbin/apach /usr/sbin/apache2 -k start
22596 /usr/sbin/apach /usr/sbin/apache2 -k start
22597 /usr/sbin/apach /usr/sbin/apache2 -k start
22598 /usr/sbin/apach /usr/sbin/apache2 -k start
23308 /usr/sbin/apach /usr/sbin/apache2 -k start
~~~

As I wrote, all values for Apache in the process stats are "0". Dovecot (as written, configured as `dovecot`):

~~~
ps -eo pid,comm,command|grep dovecot
 3127 dovecot         /usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
 3129 anvil           dovecot/anvil
 3130 log             dovecot/log
21449 grep            grep dovecot
~~~

Makes 3 processes, while Monitorix shows only 1. So let me ask: Which line(s) do you count, those having the "name" in "comm" – or in "command"? The first would explain things here due to the truncated field at least for Apache and Amavis, and also explain it for Dovecot as only one line has "dovecot" in the "comm" field.

For confirmation, I will now change my config:

* `apache2` → `/usr/sbin/apach`
* `amavisd-new` → `/usr/sbin/amavi`
* Nothing I could do to match the other Dovecot processes :(

Done that, and `service monitorix restart` applied. Waiting a little, then I will reload the page (which will take a while, see the other issue ;)

OK, ***CONFIRMED:*** Both Amavis and Apache now show up with 1 process, 0 threads (Apache definitely has multiple threads, which won't show up as the string doesn't match in that place). Both also show up in context switches and memory usage, but keep on "0" for everything else (might be due to the fact they were idle in this short intervall).

@skibbipl Could you please verify my steps if they yield comparable results in your case?

@mikaku I consider this a work-around if the other stats show up correctly. Can you think of a "real solution" to that?

**Comment by mikaku** [comment]
@IzzySoft,

If you get this:

```
ps -eo pid,comm,command|grep amavis
21316 grep            grep amavis
23347 /usr/sbin/amavi /usr/sbin/amavisd-new (master)
23367 /usr/sbin/amavi /usr/sbin/amavisd-new (ch2-avail)
23368 /usr/sbin/amavi /usr/sbin/amavisd-new (ch2-avail)
```

then you should configure it as `/usr/sbin/amavi`, or use the complete command `/usr/sbin/amavisd-new (master)`, or `/usr/sbin/amavisd-new (ch2-avail)`.

The same for Apache, use `/usr/sbin/apach` or `/usr/sbin/apache2 -k start`.

> So let me ask: Which line(s) do you count, those having the "name" in "comm" – or in "command"?

Monitorix first compares your process name string with the string in the `comm` column. If nothing matches there then it attempts by comparing it with the string in the `command` column.

>  I consider this a work-around if the other stats show up correctly. Can you think of a "real solution" to that?

This is the way how it works.

When doing this graph I saw really weird process names, even some of them with spaces in the middle! (yeah, terrible).

I ended up thinking that the best way is how Monitorix is doing it right now, that is, just picking the process name as it is in the `comm` column or as it is in the `command` column.

**Comment by IzzySoft** [comment]
@mikaku 

> Monitorix first compares your process name string with the string in the `comm` column. If nothing matches there then it attempts by comparing it with the string in the `command` column.

So with the Apache example, if I configured it as `apach`, it should match both columns (substring) – or must it be a "complete match" (full string must be equal)?

I've experimented a little with your `ps` command – looks like I have to live with the work-around, as the `comm` field is buggy in Debian Wheezy ARMHF: no matter what, it always puts `/usr/sbin/apach` (though according to the man page, the column shouldn't be truncated when it's the last).

**Comment by mikaku** [comment]
> So with the Apache example, if I configured it as apach, it should match both columns (substring) – or must it be a "complete match" (full string must be equal)?

No, Monitorix don't makes use of substrings, it uses a simple comparison.

> I've experimented a little with your ps command – looks like I have to live with the work-around, as the comm field is buggy in Debian Wheezy ARMHF: no matter what, it always puts /usr/sbin/apach (though according to the man page, the column shouldn't be truncated when it's the last).

The column `comm` is 15 characters wide. That's not a bug, but a kernel feature. :)

> PS: Might I suggest placing a comment in the corresponding config place?

Actually the `monitorix.conf(5)` man page has the following commentary on this:

*Monitorix  uses  the  following  command  to  find the processes listed in this option:*
`# ps -eo pid,comm,command`

It's not a problem for me to change it by your message, which probably clarifies better that process.
Thanks.

**Comment by skibbipl** [comment]
I use `Linux server 4.2.0-1-amd64 #1 SMP Debian 4.2.1-2 (2015-09-27) x86_64 GNU/Linux` kernel
I've checked my config and had to replace httpd with apache2. But still I can't get any network info. Here are my results:
```
# ps -eo pid,comm,command|grep apache2
 8336 apache2         /usr/sbin/apache2 -k start
28167 apache2         /usr/sbin/apache2 -k start
28187 apache2         /usr/sbin/apache2 -k start

# ps -eo pid,comm,command|grep sshd
 4021 sshd            sshd: skibbi [priv]
 4027 sshd            sshd: skibbi@pts/0
 8228 sshd            /usr/sbin/sshd -D
 9856 sshd            sshd: root@pts/2
10102 sshd            sshd: skibbi [priv]
10104 sshd            sshd: skibbi@notty

# ps -eo pid,comm,command|grep postgres
23553 postgres        /usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
23554 postgres        postgres: startup process   recovering 00000001000000020000004F
23555 postgres        postgres: checkpointer process
23556 postgres        postgres: writer process
23558 postgres        postgres: stats collector process
25684 postgres        postgres: wal receiver process   streaming 2/4F2FA718
```
and corresponding io stats:
```
apache:
# cat /proc/8336/io
rchar: 12580276
wchar: 150219092
syscr: 82925
syscw: 58301
read_bytes: 4497408
write_bytes: 57233408
cancelled_write_bytes: 0

sshd:
# cat /proc/8228/io
rchar: 235962399761
wchar: 135804066432
syscr: 45816892
syscw: 5458161
read_bytes: 19892658176
write_bytes: 79062458368
cancelled_write_bytes: 1146880

postgres:
# cat /proc/23553/io
rchar: 2664000470
wchar: 2732145753
syscr: 7536467
syscw: 1540079
read_bytes: 7081984
write_bytes: 4671700992
cancelled_write_bytes: 135168
```

**Comment by mikaku** [comment]
@skibbipl,

Thanks for the information provided.

You are not getting *any* data in the network graph *only* for Apache? or you are getting a complete blank network graph? (which would mean that Monitorix is not collecting network information for any process).

Also, in order to make sure that the file `io` has not changed in the latest kernel, can you please, edit that file (with `vi` preferably) and make sure that each line terminates with the last character? I mean, with no trailing spaces or any other character.

Thanks.

**Comment by skibbipl** [comment]
Yes, I'm not getting any data. In fact I discovered that monitorix probably gets some data just between daemon reatarts (see the spikes - it's when I restarted service):
![process04z 1day](https://cloud.githubusercontent.com/assets/4746858/10333444/4af9772a-6ce4-11e5-8748-c838a1abd2a1.png)

**Comment by mikaku** [comment]
@skibbipl,

Can you please set the option `show_gaps` to `n`?
Just to make sure that there is any problem while plotting data.

**Comment by skibbipl** [comment]
Yep, switching show gaps fixed the problem.

**Comment by mikaku** [comment]
OK, I'll concentrate on this.
Thanks.

**Comment by mikaku** [comment]
I've just discovered that the values collected for the network graph are sometimes negatives, which would mean that such values are not as accurate as they should. Perhaps it's time to not use the `io` file anymore and use another source of information.

```
Wed Oct  7 11:54:00 2015 - process::process_update: N:0.0293784362278088:729714688:6075.73333333333:-354.266666666667:1678:...
```

Here the value `-354.266666666667` belongs to the network data. Such negative value will be converted automatically to `NaN` by RRDtool. That's the reason why the network graph is not showing real values and also why there are so many gaps in the graph.

**Comment by mikaku** [comment]
@skibbipl,

I've find out the cause of these negative values. When Monitorix collects data on every minute, it may be processes, like Apache, that have more than one process (i.e. it has threads), and Monitorix summarizes all together. That's correct.

Then on the next minute, it repeats the procedure and after summarizing the network usage of all Apache processes, Monitorix subtracts the value of the previous minute from that one. Just to make sure to show the network data used during this last minute.

It turns out that this time it may not be the same number of Apache processes, it could be that there are less than the previous minute, and hence, the total of network usage is less than the previous minute. Therefore after subtracting the value of the previous minute (which is greater) it creates a negative value.

It makes sense to me, so I won't touch anything on Monitorix other that ensure to convert those negatives values to zero, denoting that in the present minute the network usage was less than in the previous minute.

Also, with zero values those annoying gaps will disappear.

I hope that clears up things.

**Comment by IzzySoft** [comment]
@mikaku 

> It's not a problem for me to change it by your message, which probably clarifies better that process.

As you prefer :) I was suggesting that short comment directly in the config. And with your latest feedback, I'd even change my message a little:

~~~
<process>
   # names in the process list must *EXACTLY* correspond to those in the "comm"
   # (or "command") field of 'ps -eo pid,comm,command' (no substring, no wildcard)
   <list>
   …
~~~

You could add something like "for details, see "man 5 monitorix.conf", of course :)

**Comment by mikaku** [comment]
@IzzySoft,

Your last message is much better and really clarifies things. :)

I don't like to put commentaries in the config file because after certain number of updates people may have old configuration files without those commentaries reflected there in.

Let's put it in the man page which is where people should refer for these and other things.

**Comment by IzzySoft** [comment]
@mikaku 

> It makes sense to me, so I won't touch anything on Monitorix other that ensure to convert those negatives values to zero, denoting that in the present minute the network usage was less than in the previous minute.

Not sure that's 100% correct then. Playing an example

~~~
Snapshot   Apache proc's  Comment
1            45           10 of them catering for high load (e.g. download of huge files)
2            38           7 of the "high load" proc's done, 3 still doing high load
3            35           all high-load done, still 20 care for several web pages
~~~

According to your note, that would be a "peak" at snap-1, while reporting "zero traffic" for 2+3 – which doesn't really reflect reality. Still:

> Also, with zero values those annoying gaps will disappear.

Agreed with that, so we definitely can count it an improvement. Remaining question is still if we can do better (without too much overhead, such as remembering each PID for comparison).

----

> Your last message is much better and really clarifies things. :)

Glad you like it! Feel free to use it :)

> I don't like to put commentaries in the config file because after certain number of updates people may have old configuration files without those commentaries reflected there in.

> Let's put it in the man page which is where people should refer for these and other things.

Agreed. My fault to push you to modularity back then *LOL* – but I really like the current way. And after all, if I would have checked better, there's that line 3 in the config file: "See monitorix.conf(5) manpage for a detailed description of each option." Convinced me :)

**Comment by mikaku** [comment]
@IzzySoft,

> Agreed. My fault to push you to modularity back then LOL – but I really like the current way. And after all, if I would have checked better, there's that line 3 in the config file: "See monitorix.conf(5) manpage for a detailed description of each option." Convinced me :)

LOL, didn't even remember the existence of that line!

**Comment by IzzySoft** [comment]
@mikaku To be honest: neither did I. I just wanted to ask you having at least that included, when – shame on me! – I found it was already there :)

Thanks for the update to the man page – yes, no doubts left now I'd say.
