### ISSUE TITLE
Make possible to monitor more than one nginx server

### ISSUE THREAD

**Issue by k3a** [mikaku/Monitorix#126]
Is there any technical reason why only one Nginx server can be monitored? 
There is "list" parameter for Apache and Lighttpd but unfortunately no for Nginx.

**Comment by mikaku** [comment]
Since Nginx doesn't offer any network usage statistics, Monitorix needs to use `iptables` which will only work on local installations. The graph assumes you only have one instance of Nginx running in the same system.

I don't know if newer Nginx versions already show network usage in its stats, if so, I could introduce the `list` option in order to support remote Nginx installations.

**Comment by k3a** [comment]
Ah, I see. The standard 'stub_status' doesn't include any traffic data and there is a 'status' extension which is only part of Nginx Pro. Closing the task then.
