### ISSUE TITLE
Feature request: php-fpm support

### ISSUE THREAD

**Issue by ZalemCitizen** [mikaku/Monitorix#167]
What about reading FPM status page and display idle/busy workers, etc ?
Thx

**Comment by W4U-TOURS** [comment]
+1 for adding FPM status

**Comment by mikaku** [comment]
I've been tinkering a bit with the status returned by PHP-FPM:

```
pool:                 pool1
process manager:      dynamic
start time:           17/Mar/2019:11:14:02 +0100
start since:          856944
accepted conn:        14466
listen queue:         0
max listen queue:     1
listen queue len:     128
idle processes:       6
active processes:     1
total processes:      7
max active processes: 5
max children reached: 0
```

1. It looks like the value of `start since:` is common in all pools. Is this right?
1. My version of PHP-FPM don' show the option `slow requests:`, even when I've setup:
```
request_slowlog_timeout = 5s
slowlog = /var/log/php-fpm/pool1-slow.log
```
1. Finally, if I append the string `/?full` in the URL, it gives more information regarding the threads used for that pool. I don't see relevant that information.

In all, I could prepare a new graph like the following one:

```
+-----------------------------------+------------------+
|      idle processes               |  listen queue    |
|      active processes             +------------------+
|      total processes              | max active proc  |
+-----------------------------------+------------------+
|                                   |   slow requests  |
|      active processes             +------------------+
|                                   |    uptime        |
+-----------------------------------+------------------+
```

We do agree?

**Comment by mikaku** [comment]
The following is an example of what I have don so far (almost completed):

![phpfpm](https://user-images.githubusercontent.com/829885/55497174-106db900-5641-11e9-9627-06c88eef9528.png)
