### ISSUE TITLE
Monitorix being connected to some malicious hosts - vulnerability?

### ISSUE THREAD

**Issue by niutech** [mikaku/Monitorix#168]
I have been running Monitorix 3.8.1 under Debian Jessie (`Linux 3.16.0-4-amd64`) on `myhost.com:8081` (`tproxy`). However, I can see many malicious connections on this port using `netstat -p`:

```
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp      154      0 myhost.com:tproxy     mail.picdown.me:46356   CLOSE_WAIT  -
tcp      154      0 myhost.com:tproxy     mail.picdown.me:59991   CLOSE_WAIT  -
tcp      121      0 myhost.com:tproxy     227-145-172-163.r:54204 CLOSE_WAIT  -
tcp      154      0 myhost.com:tproxy     no-reverse-dns-co:38395 CLOSE_WAIT  -
tcp        0      0 myhost.com:tproxy     122.224.153.109:39987   ESTABLISHED 1046/monitorix-http
tcp      154      0 myhost.com:tproxy     no-reverse-dns-co:37571 CLOSE_WAIT  -
tcp      196      0 myhost.com:tproxy     163-172-68-183.re:58072 CLOSE_WAIT  -
```

For example, [122.224.153.109](http://122.224.153.109.ipaddress.com/) is an address in China. Does it mean Monitorix is vulnerable and I have been hacked?

**Comment by mikaku** [comment]
@niutech,

As long as you have a public server on Internet you should expect a lot of daily remote connections on HTTP, SSH, FTP, etc. and other well-known ports like 8080, 8081, etc. trying to discover the software that runs behind (WordPress, PHPAdmin, etc.) in order to be able to take advantage of a software vulnerability.

You can mitigate these remote connections to Monitorix by using the Basic Authentication mechanism included in its built-in HTTP server, or using third-party tools with GeoIP to avoid connections from certain countries.

All software is exposed, Monitorix included. That's one of the reasons to keep up to date your server.

**Comment by niutech** [comment]
So I suppose it is secure as long as I have authentication enabled,
isn't it? How to tell if my server is behaving normally and isn't
hacked, using netstat? Thanks!

**Comment by mikaku** [comment]
@niutech,

> So I suppose it is secure as long as I have authentication enabled, isn't it?

I can't ensure you that your server will be secure forever even with authentication enabled, because it depends if the network from where you are authenticating is secure. What I said is that enabling Basic Authentication will help you to reduce all these remote connections.

> How to tell if my server is behaving normally and isn't hacked, using netstat?

This question is out of the scope of Monitorix. Anyway, I don't think `netstat` will tell you if your server is being hacked or not.

Watching some graphs in Monitorix will help you to recognize attacks in SMTP, HTTP, SSH, FTP, etc. Also, watching your system logs, checking processes regularly, etc. will also help you to discover malicious behaviors against your server.

**Comment by IzzySoft** [comment]
@niutech if you want to secure your server a little better, I recommend you take a look at fail2ban. Ships in the standard repos of Jessie. You could create specific rules on log entries you see and have fail2ban block "bad users' IPs" (e.g. those who try to access `/wp-admin` and the like, i.e. typical Wordpress etc. attacks). Monitorix then even can show in a graph how many of the bad guys you've "caught". Basically, fail2ban does part of what @mikaku just recommended: "watching your system logs" :)

Additional protection possibilities include running Monitorix within Apache, and protect Apache with specific mods. Much more possibilities in terms of rules then, e.g. when using mod_security:

![fail2ban0 1day](https://cloud.githubusercontent.com/assets/6781438/19748523/9d9a7f8c-9be2-11e6-91b2-c4bb75db31e7.png) 
![fail2ban1 1day](https://cloud.githubusercontent.com/assets/6781438/19748539/bcbfe352-9be2-11e6-9572-d7a8e0641b83.png)
