### ISSUE TITLE
Request: Battery status

### ISSUE THREAD

**Issue by Almtesh** [mikaku/Monitorix#170]
It would be great to have the battery statuses in monitorix.
For the moment, I used a workaround like this one:
```plain
# GENSENS graph
# -----------------------------------------------------------------------------
<gensens>
        <list>  
                0 = temp0, temp1
                1 = cpu0, cpu1, cpu2, cpu3
        </list>
        <desc>  
                temp0 = /sys/class/power_supply/BAT0/current_now
                temp1 = /sys/class/power_supply/BAT0/capacity
                cpu0 = /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
                cpu1 = /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq
                cpu2 = /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq
                cpu3 = /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq
        </desc>
        <unit>  
                temp0 = 1000000
                temp1 = 1
                cpu0 = 0.001
                cpu1 = 0.001
                cpu2 = 0.001
                cpu3 = 0.001
        </unit>
        <map>   
                temp0 = Courant
                temp1 = Charge
                cpu0 = CPU 0
                cpu1 = CPU 1
                cpu2 = CPU 2
                cpu3 = CPU 3
        </map>
        rigid = 0, 0
        limit = 100, 100
</gensens>
```
But the current and the charge a shown in celsius and I don't know how to watch the full capacity.

**Comment by mikaku** [comment]
Hi,

I was revisiting this issue, and comparing the values you have in your `BAT0` directory they look different than what I have in my laptop with a Fedora 29 running the Linux kernel v5.0.8:

```
# ls -l
total 0
-rw-r--r--. 1 root root 4096 Apr 25 16:59 alarm
-r--r--r--. 1 root root 4096 Apr 25 16:59 capacity
-r--r--r--. 1 root root 4096 Apr 25 16:59 capacity_level
-r--r--r--. 1 root root 4096 Apr 25 16:59 cycle_count
lrwxrwxrwx. 1 root root    0 Apr 25 16:59 device -> ../../../PNP0C0A:03
-r--r--r--. 1 root root 4096 Apr 25 16:59 energy_full
-r--r--r--. 1 root root 4096 Apr 25 16:59 energy_full_design
-r--r--r--. 1 root root 4096 Apr 25 16:59 energy_now
-r--r--r--. 1 root root 4096 Apr 25 16:59 manufacturer
-r--r--r--. 1 root root 4096 Apr 25 16:59 model_name
drwxr-xr-x. 2 root root    0 Apr 25 16:59 power
-r--r--r--. 1 root root 4096 Apr 25 16:59 power_now
-r--r--r--. 1 root root 4096 Apr 25 16:59 present
-r--r--r--. 1 root root 4096 Apr 25 16:59 serial_number
-r--r--r--. 1 root root 4096 Apr 25 16:59 status
lrwxrwxrwx. 1 root root    0 Apr 25 16:59 subsystem -> ../../../../../../../../../class/power_supply
-r--r--r--. 1 root root 4096 Apr 25 16:59 technology
-r--r--r--. 1 root root 4096 Apr 25 16:59 type
-rw-r--r--. 1 root root 4096 Apr 25 16:59 uevent
-r--r--r--. 1 root root 4096 Apr 25 16:59 voltage_min_design
-r--r--r--. 1 root root 4096 Apr 25 16:59 voltage_now
```

I could create a new keys named `bat0`, `bat1`, and so on, and in the `<unit>` section you'd define the capacity, probably using the `capacity` value.

But since I don't have the value `current_now`, I don't know if `power_now` is the new name for newer kernels, or that value is not fixed in all laptops, etc., which would complicate things.

I need more information to have clear what are the definite values.

Any thoughts?

**Comment by Almtesh** [comment]
Actually, it depends on the hardware, not the kernel version. With the same kernel version (on Debian Stretch), I found, depending on the hardware, `charge_now` or `energy_now` and the battery was called `BAT` or `BAT0`.

**Comment by mikaku** [comment]
I see, I understand that  `BAT` o `BAT0`, or even `BAT1` are just directory names.

I'd like to know if the following configuration type would suffice for all the cases (I've omitted the references to `temp[n]` and `cpu[n]` to minimize the example:

```
# GENSENS graph
# -----------------------------------------------------------------------------
<gensens>
        <list>  
                0 = bat0
        </list>
        <desc>  
                bat0 = /sys/class/power_supply/BAT0/current_now
        </desc>
        <unit>  
                bat0 = capacity
        </unit>
        <map>   
                bat0 = Charge
        </map>
        rigid = 0, 0
        limit = 100, 100
</gensens>
```

As you can see, the `<unit>` section here would indicate the top value of the battery, used as the 100% in the graph.

What do you think?

**Comment by Almtesh** [comment]
Nice, I can do that?
Unfortunatly, I changed the hardware I used, I updated my Debian, so I don't have anymore this instance of monitorix.

**Comment by mikaku** [comment]
Well, that was just an example of how it could be implemented. That's why I asked you if you think it would be useful.

So, if I understand correctly you no longer will be able to test it?

**Comment by mikaku** [comment]
I've made some changes in the example, since I see in the kernel documentation that the value `capacity` means the percentage of the battery capacity. With that value combined with a `rigid = 2` and  `limit = 100` would be enough to see the battery percentage.

**Comment by Almtesh** [comment]
Actually, I got hardware and environment to test it, if you want to.

**Comment by mikaku** [comment]
OK, give me more time to make some changes in `gensens.pm` to include the battery functionality.

**Comment by mikaku** [comment]
I've rewritten completely this module (`gensens.pm`) so it can hold now battery values as its third supported sensor. It is no longer so rigid as it was before in the sense that it can also hold multiple graphs with `temp`, `cpu` or `bat` as its (so far) unique sensors supported, and in any order.

Of course, it cannot supports mixed sensors in a the same group listed in the `<list>`option. If you need more temperature sensors, just create a new group in `<list>`.

The new version of this module is capable to identify the type of the group by searching the substrings `temp`, `cpu` and `bat`, so it will put automatically the vertical label accordingly (`Celsius` or `Fahrenheit`, `Hz` or `Charge`).

The new `<title>` option helps to define the proper title for each group or graph.

As you can see, since the battery value is a percentage, you are encouraged to set the values `rigid` and `limit` accordingly, to scale correctly the graph.

The following is an example of the new `<gensens>` section in the configuration file:

```
# GENSENS graph
# -----------------------------------------------------------------------------
<gensens>
        <list>
                0 = temp0, temp1
                1 = cpu0, cpu1, cpu2, cpu3
                2 = bat0
        </list>
        <title>
                0 = Temperatures
                1 = CPU frequency
                2 = Battery status
        </title>
        <desc>
                temp0 = /sys/devices/virtual/thermal/thermal_zone0/temp
                temp1 = /sys/devices/virtual/thermal/thermal_zone1/temp
                cpu0 = /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
                cpu1 = /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq
                cpu2 = /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq
                cpu3 = /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq
                bat0 = /sys/class/power_supply/BAT0/capacity
        </desc>
        <unit>
                temp0 = 1000
                temp1 = 1000
                cpu0 = 0.001
                cpu1 = 0.001
                cpu2 = 0.001
                cpu3 = 0.001
                bat0 = 1
        </unit>
        <map>
                temp0 = Temperature Zone 0
                temp1 = Temperature Zone 1
                cpu0 = CPU0 frequency
                cpu1 = CPU1 frequency
                cpu2 = CPU2 frequency
                cpu3 = CPU3 frequency
                bat0 = Battery 0
        </map>
        <alerts>
        </alerts>
        rigid = 0, 0, 2
        limit = 100, 100, 100
</gensens>
```

The following is a screen shot of this configuration after running for a while:

![gensens](https://user-images.githubusercontent.com/829885/57077753-19f44a80-6ced-11e9-9bcf-082c7c2a5c48.png)

**Comment by mikaku** [comment]
Please, consider update your Monitorix installation by downloading from GitHub the latest `monitorix`, `lib/gensens.pm` and upgrade your `monitorix.conf` file accordingly.

Then, restart Monitorix and let me know if it works fine for you.
