### ISSUE TITLE
Toggle off background red color feature in port.pm module 

### ISSUE THREAD

**Issue by WyRe** [mikaku/Monitorix#182]
After talking with @mikaku on IRC he has concluded this feature could be deprecated, however, somebody could still found it interesting and will be fine to add a trigger to control the feature.

Regards.

**Comment by mikaku** [comment]
Thanks @WyRe,

That old feature appeared when *port.pm* module was created to control the network port of each listening service. So, if Monitorix detects that one of these ports is not listening, it just advices the user changing the background color of the graph.

This indeed has no sense nowadays since you can monitor any network port (listening or not), but since someone might still find such feature interesting, I will include an specific option to keep toggle that feature on or off.

**Comment by mikaku** [comment]
This commit should fix that issue.
