### ISSUE TITLE
swap monitoring - Ubuntu Server 17.10.1

### ISSUE THREAD

**Issue by wmyrda** [mikaku/Monitorix#202]
I installed for tests Ubuntu Server 17.10.1 (kernel  4.13.0-32-generic) and have noticed on default install following message:

Tue Feb 20 11:14:40 2018 - fs::fs_init: Unable to detect the device name of 'swap', I/O stats won't be shown in graph. If this is really a mount point then consider using <devmap> to map it manually to a device name.

"Top" properly reports presence and use of swap memory so it is definitely not due to missing system. 

I tried to reproduce it on my Gentoo machine (kernel 4.14.11) as well as Ubuntu Server 16.04.3 and I did not notice such an error.

**Comment by mikaku** [comment]
Such error message means that since Monitorix is unable to detect the device name where swap resides, then you won't see swap activity in the I/O graph. To show swap I/O activity it must reside on a disk device in order to get the activity counters provided by the kernel.

That doesn't mean that swap won't be represented in the filesystem usage graph.

**Comment by wmyrda** [comment]
Ubuntu has set up following entry in the following location in /etc/fstab
/swapfile                                 none            swap    sw              0       0

It does differ from regular entry which usually points to the "dev" instead of regular file in the system as such:
/dev/zvol/datastore/SWAP    none              swap    sw              0      0

Does that make it problematic for Monitorix to see it?

**Comment by mikaku** [comment]
That's it, as you can see your system is using a simple file as its swap area. Hence, your swap doesn't resides in its own device name, and that's what Monitorix is telling you.

As i said, you can continue seeing your swap use in the usage graph, but you won't be able to see the I/O activity of your swap area, because kernel doesn't counts activity on a file.

I hope that clear up things.
