### ISSUE TITLE
Conflict with webmin and virtualmin

### ISSUE THREAD

**Issue by parsisan** [mikaku/Monitorix#208]
hi guys,
i have an issue with monitorix and webmin+virtualmin on ubuntu.

monitorix work fine in first access from url. but for second time it not work.

159.******* refused to connect.
Search Google for 159.******* 8080 monitorix cgi
ERR_CONNECTION_REFUSED

i should restart monitorix service manually again.

can you provide a solution.
thanks

**Comment by mikaku** [comment]
Hi @parsisan,

I don't know what means the `159` here. Make sure that Monitorix is really running when you receive the `refused to connect` message.

Also, it might be possible your Webmin software is trying to connect to `localhost` and your system is prioritizing IPv6 over IPv4. For instance, look at the following examples trying to connect to Monitorix listening in port 8080:

1. Connecting to localhost IPv4 (127.0.0.1):
```
$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /monitorix HTTP/1.1
HOST: localhost

HTTP/1.0 200 OK
Date: Fri, 04 May 2018 10:20:08 +0200
Server: Monitorix HTTP Server
Connection: close
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html "-//W3C//DTD HTML 4.01 Final//EN">
<html>
 <head>
  <title>Place a title here</title>
  <link rel="shortcut icon" href="/monitorix/monitorixico.png">
 </head>
[...]
```

2. Connecting to localhost IPv6 (::1):
```
$ telnet ::1 8080
Trying ::1...
telnet: connect to address ::1: Connection refused
```

Now look if I use the hostname `localhost` instead of the IP:
```
$ telnet localhost 8080
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /monitorix HTTP/1.1
HOST: localhost

HTTP/1.0 200 OK
Date: Fri, 04 May 2018 10:25:45 +0200
Server: Monitorix HTTP Server
Connection: close
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html "-//W3C//DTD HTML 4.01 Final//EN">
<html>
 <head>
  <title>Place a title here</title>
  <link rel="shortcut icon" href="/monitorix/monitorixico.png">
 </head>
```

As you can see telnet is trying IPv6 first, and if it fails it tries IPv4.
I hope that helped you.
