### ISSUE TITLE
Monitorix stops collecting data on high system loads

### ISSUE THREAD

**Issue by duc996** [mikaku/Monitorix#230]
On my system a backup is started every day at 22h. Monitorix often stops collecting data at the same time. The system load is high at this moment. Heavy disk io with zfs seems to block the system for more then one second.

I have checked procfs for child processes of monitorix. There is no child process running.

After sending a alarm signal via kill, Monitorix restarts reporting data (a service restart also works).

Version: 3.11.0
System: Ubuntu 16.04.6 LTS (Perl: v5.22.1)

![system1z 1week](https://user-images.githubusercontent.com/2356813/55322995-11a2b880-547e-11e9-95bd-9c78ee0e6bed.png)

**Comment by duc996** [comment]
I have the same behavior with version 3.10.1 (only replacing /usr/bin/monitorix).

![Screenshot from 2019-04-02 09-21-30](https://user-images.githubusercontent.com/2356813/55384171-42402c00-552a-11e9-90bc-a89d675b1c5f.png)

And the stack trace in procfs:
[<ffffffff8109764b>] sys_pause+0x2b/0x50
[<ffffffff8186145b>] entry_SYSCALL_64_fastpath+0x22/0xcb
[<ffffffffffffffff>] 0xffffffffffffffff

Process statistics don't change (/stat) anymore.

**Comment by mikaku** [comment]
I'm unable to reproduce this even on a very high peaks of CPU load.
Anyway, I've patched with #231 almost all my servers (CentOS 4, 5, 6 and 7) in order to let me check if something goes wrong with your suggested changed to `select()`.

I'd like that more people would test this on newest Linux systems, and even on *BSD systems.

So, let's run it for a while to see how it works.

**Comment by mikaku** [comment]
The FreeBSD user @abqcheeks tested your patch #230 on different FreeBSD versions with successful results. :smiley:

**Comment by mikaku** [comment]
All my patched servers are also working fine, so let's push it!
