### ISSUE TITLE
Filesystem usage issue with space in fs name

### ISSUE THREAD

**Issue by sfatula** [mikaku/Monitorix#234]
I have a filesystem named /home/VIrtual Machines. I have tried lots of different syntax to get it to even show on the web page, and, the only one that seems to acquire any percent usage is using /home/Virtual\ Machines. So, the name now shows up on the graph with the slash in it, so, I decide I wil use <desc> to rename it, but, no syntax I have discovered allows me to do that. Also, I want to send an alert but there also, no syntax I have found allows me to get alerts for this filesystem. I suspect a problem handling the space in the filesystem. 

Do you need anything else to help?

**Comment by mikaku** [comment]
Well, sincerely, I'd never think that someone would create a mounting point name with spaces on it. I think it's a bad practice, and might bring some problems with other system tools.

Nevertheless, I'm able to fix part of the problem in Monitorix but not all. I mean, I can fix that you can monitor the file system usage and its disk i/o even on a mounted directory containing spaces, but you won't be able to change its name nor make any class of alert.

Why? because as you might notice, the name of the mounting point (the directory name) is used as a key in the options `<desc>` and `<alerts>` which expects a value.

The Perl module that Monitorix uses to parse the configuration file doesn't support keys that contain spaces in their names. Just like this:

/mnt/32 GB = 32GB USB Pendrive
/home/Virtual Machines = VMs

The same for the Alerts, which also use these names as the key in the key/value pairs.

**Comment by sfatula** [comment]
I have never had any problem with any tool ever with spaces in names (more than 10 years), however, the fact that I cannot use alert means it is worth it to me to remove the space.
