### ISSUE TITLE
Support logging to systemd

### ISSUE THREAD

**Issue by kyak** [mikaku/Monitorix#268]
As discussed on IRC, it would be a nice feature for Monitorix to support logging to systemd instead of a log file.

My understanding is that it is enough to simply have an option to spit out messages to stdout instead of a log file. The rest can be handled in systemd unit file.

This would be very convenient for people using systemd/journalctl to view and manage their log files all on one place.

**Comment by mikaku** [comment]
Hi, I have some questions:

1. What changes should be made in the systemd unit file?
1. Does changes will be compatible for those that prefer to continue using the log file?

Thanks.

**Comment by kyak** [comment]
Hi!

1. There are no systemd specific changes required in the unit file. If monitorix is able to log to stdout, systemd will handle the rest.
2. Compatibility with using regular log file can be preserved by e.g. making monitorix log to file by default and log to stdout when user specifies an option.

**Comment by mikaku** [comment]
@kyak, sorry for taking so long to comment here.

AFAIK a daemon can't write to stdout device because it's not attached to any tty.
Do you have an example of another application doing what you suggest?

**Comment by kyak** [comment]
@mikaku no problem!

Maybe you should not detach from stdout/stderr when daemonizing? I'm not sure about how other applications do that; but I've seen that a regular application (not a daemon) logging to stdout works perfectly fine with systemd and its journal.

**Comment by mikaku** [comment]
I've made some changes in the way how Monitorix daemonize itself but I don't see messages in the standard log files.
Can you provide me the right command to debug if Monitorix is logging via systemd?

**Comment by mikaku** [comment]
I've finally managed to log on `systemd`.

This is how it will work. The option `log_file` is currently by default set to `/var/log/monitorix` which is the file where Monitorix logs all the messages. From now on, if that option is not defined or leaved blank Monitorix will use the standard file descriptors to do logging.

On a `systemd`-based system such file descriptors will be managed by `systemd` and you'll be able to see the Monitorix log messages just using the command `journalctl -u monitorix`.

@kyak, please, download the latest version of `/usr/bin/monitorix`, modify your `/etc/monitorix/monitorix.conf` file so that the option `log_file` is set undefined and restart Monitorix.

Just let me know if it works as expected.

**Comment by kyak** [comment]
@mikaku nice, thanks! Logging to systemd works as expected.

One question though. There are two `log_file` options in `monitorix.conf`. I've commented out the option from the main section. But there is another one for the built-in httpd. What should I do with that option?

**Comment by mikaku** [comment]
@kyak, please try again with the latest changes.

You'll need to download the files ` lib/HTTPServer.pm` and  `lib/Monitorix.pm`.

**Comment by kyak** [comment]
@mikaku Thanks, works great!
