### ISSUE TITLE
device /dev/shm not recognized

### ISSUE THREAD

**Issue by zd59** [mikaku/Monitorix#275]
Hi!

I use Monitorix to monitor on a Linux server with high /dev/shm usage.
I wish to include that device in a FS but it failed to recognize:
`fs::fs_init: Unable to detect the device name of '/dev/shm', I/O stats won't be shown in graph. If this is really a mount point then consider using <devmap> to map it manually to a device name.`
The special device is not listed in /proc/diskstats, so I have no option to list it in <devmap>
How to convince monitorix to recognize it? Or this is not possible?

**Comment by zd59** [comment]
Hello again!

The above `Unable to detect..` issue is a false. 
This is issue is reported in a monitorix log file, but detection works and graph data is correct.
Please remove this false positive.

**Comment by mikaku** [comment]
Hello,

That message is correct.

As you might know, the `fs.pm` module shows 4 different graphs. The two graphs in the right side show I/O activity of the device where the file system is mounted on. Since `/dev/shm` is not a disk drive, but a memory mapped device, the Linux kernel doesn't include it in `/proc/diskstats` and hence these two graphs won't show any data from that file system.

The message only warns you about this.

**Comment by zd59** [comment]
Thank you for a clarification.
