### ISSUE TITLE
Adapting Monitorix to run as regular user (not root) 

### ISSUE THREAD

**Issue by IDoProgramming** [mikaku/Monitorix#288]
Due to it's low footprint Monitorix seems to be a good candidate to be run on many different platforms that do not provide users with any means of monitoring resources by default and do not necessarily provide root level access to the system. 

Good example would be 
* shared web hosting environment allowing access to specified ports  
* general shell account server allowing access to specified ports  

By explicit separation of parts that  absolutely require root access and these that do not (like non root users and/or groups)  users of such environments would be able to monitor state of their accounts without need to modify existing code base on their own. 

In case that some functionalities of module are 
*  too hard/impossible to be separated 
 * access to a functionality may differ among many different variants of operating system (on some systems it do require root rights and do not on other) 

but the module as whole could operate as regular user an error message of some sort (possibly logged to a file) or other form of warning about that fact and/or failure of access to root would be preferred over termination of whole Monitorix if access to such resources is not absolutely crucial to run Monitorix.

Would such adaptation be possible?

**Comment by mikaku** [comment]
Theoretically yes, it would be possible, but I see these issues:

- You'll have to `chown` the directory in `base_lib` option (formerly `/var/lib/monitorix`) and all its subdirectories to give write permissions to the regular user under which Monitorix will run.
- You'll also have to give write permissions to the two Monitorix log files to give write permissions to the same regular user (also, you'll have to create the log files by hand since the directory `/var/log` is not writable by a regular user) . If you rotate these log files, you'll have to make sure to create the new one with proper permissions.
- As you already noticed, there would be some modules that won't work because they need `root` permissions to collect statistics.

**Comment by mikaku** [comment]
In order to force Monitorix to run as a regular user (the user who started it), you must add the new argument `-u` in the command line.

Remember that the regular user must have write permissions to the whole tree in `/var/lib/monitorix`.

Just let me know how it works.
