### ISSUE TITLE
Missing imgs directory

### ISSUE THREAD

**Issue by Termplexed** [mikaku/Monitorix#328]
Not sure if this should be reported to Rehberg or here. But anyhow:

Installed by using .deb package from his site. (`monitorix_3.13.1-izzy1_all.deb`) It works fine besides install not creating the `imgs` directory. The Makefile has it so not sure what is happening:

https://github.com/mikaku/Monitorix/blob/0ed93455e243fd15ec03010084b22dac32435055/Makefile#L50

	$(INSTALL_WORLDDIR) "$(DESTDIR)$(WWWDIR)/imgs"

Easy solved by `mkdir`, but as a heads up. If I should direct this elsewhere somehow, do not be shy and ask.

**Comment by mikaku** [comment]
Thanks for your feedback.

Since you already talked about Andreas I. Rehberg I assume you based your installation in the `.deb` created by him.

I think that @IzzySoft creates his `.deb` package by converting the official RPM, perhaps something is missing during this conversion.

**Comment by IzzySoft** [comment]
> by converting the official RPM

Not exactly, I use the tarball. But the SPEC file has

    mkdir -p %{buildroot}%{_localstatedir}/lib/monitorix/www/imgs

so if that's the directory we're talking about, it should be created. Further, in the `.deb` file's `postinst` I see

```
chown -R www-data:nogroup /var/lib/monitorix/www/imgs
chmod 0774 /var/lib/monitorix/www/imgs
```

So if there was no error on install, the directory should be there. I wonder I don't see a `mkdir` in that file, though; maybe we/I should place an empty placeholder file into it so the packaging tool doesn't ignore creation?

@mikaku guess that is a side-effect from our trouble with permissions (internal web server vs. Apache, if you remember): I had to comment out the permission in the `%files` block – just noticed there's no mention of the `imgs` dir in there anymore at all now. But if instead I could put some `.placeholder` there, that should do the trick. Would that "hurt" anything, or would you say "go for it"?

**Comment by mikaku** [comment]
@IzzySoft thanks for your quick answer, as always.

Yes, I remember that problem with permissions but I think this is different. He talks about a nonexistent `imgs` directory which it's indeed really weird, considering that your `.deb` package was created 3 months ago and he's the first one to report it (IIRC).

Regarding your placeholder solution, I'd say *go for it!*, but let's see if he can bring more information like if he detected any error during installation, or if he discovered an `imgs` directory created in a different place, in which case it would mean that some part in the path of the `mkdir` was wrong.

**Comment by IzzySoft** [comment]
> but I think this is different.

Nope, it's exactly that: I just commented out that line and fixed the permissions in "postrun". Now ***there is no line in `%files`*** and there is no line for any file inside, so that directory is not part of the package. I didn't notice as the directory already exists on my machines. If @Termplexed did a "first time install", there should have been errors reported from `postinst` that it cannot adjust permissions on a non-existing directory.

So this could be solved by either putting a "placeholder file" inside it – or I could try to add a `mkdir` right at the place the permissions are currently adjusted (and hope that doesn't again break the packaging).

> but let's see if he can bring more information

Yes, sure. But checking the SPEC file I'm pretty sure of that's what happened. And no, the real `mkdir` wasn't touched at all, so there's no `imgs` directory created "somewhere else" suddenly. I only wonder this issue didn't come up earlier.

**Comment by Termplexed** [comment]
Thanks. Yes, you are correct, there was `postinst` errors, which made it easy enough to fix :)

```
Preparing to unpack monitorix_3.13.1-izzy1_all.deb ...
Unpacking monitorix (3.13.1-izzy1) ...
Setting up monitorix (3.13.1-izzy1) ...
[ ok ] Starting monitorix (via systemctl): monitorix.service.
chown: cannot access '/var/lib/monitorix/www/imgs': No such file or directory
dpkg: error processing package monitorix (--install):
 installed monitorix package post-installation script subprocess returned error exit status 1
```

Unpacked the .deb file locally and compared it to the Makefile, only to assert it was actually missing from the install.

```
$ tree -d deb
.
├── etc
│   ├── init.d
│   ├── logrotate.d
│   ├── monitorix
│   │   └── conf.d
│   └── sysconfig
├── usr
│   ├── bin
│   ├── lib
│   │   └── monitorix
│   └── share
│       ├── doc
│       │   └── monitorix
│       └── man
│           ├── man5
│           └── man8
└── var
    └── lib
        └── monitorix
            ├── reports
            ├── usage
            └── www
                ├── cgi
                └── css
```

**Comment by IzzySoft** [comment]
Thanks for confirming (and for reporting in the first place)! Next release should have that fixed.

**Comment by mikaku** [comment]
@IzzySoft you hit the nail. Please, let me know when you have updated your `.deb` file, so I'll refresh the website with your new version.

Thanks both.

**Comment by IzzySoft** [comment]
Oh – do you consider this worth a new release? I can of course do that. But maybe we combine that with a code update? Do you have something pending? I thought including the fix with the next release. For those affected (which seem to be very few considering it took that long to surface) there's an easy work-around, as Termplexed just proved, so I didn't feel it would be that urgent to justify a new release. But if you think it is, no big deal – I'd then just increase the suffix from `-izzy1` to `-izzy2`.

**Comment by mikaku** [comment]
> But maybe we combine that with a code update?

I don't expect a new Monitorix version within the next 6 months.

I agree that this might affect very few but, I think that Izzy products deserve more quality :smirk:. So yes, and if you don't mind, I'd like to see a new `-izzy2` version, just to make sure that everybody obtains a quality product.

**Comment by Termplexed** [comment]
Could be the solution / reason for #321 (part 2) as well if I am not mistaken.

**Comment by mikaku** [comment]
> Could be the solution / reason for #321 (part 2) as well if I am not mistaken.

Yes, but unfortunately he looks like not much responsive.

**Comment by IzzySoft** [comment]
izzy2 is ready for pickup. I've added the `mkdir` to postinst, the `.deb` has picked it up. Have not tried to install it, though – but as that was the only change, I don't see what should have broken. Maybe @Termplexed can give it a try and report back, so the issue can be closed then?

**Comment by Termplexed** [comment]
Sure. Have purged the system for anything `monitorix` and test as soon as it is up at https://apt.izzysoft.de/ubuntu/dists/generic/ (or wherever you see fit).

**Comment by mikaku** [comment]
> izzy2 is ready for pickup.

I've just updated the downloads page of the Monitorix web site.
Thanks @IzzySoft for your quick reaction.

@Termplexed if you find an unexpected issue with this new version we can reopen the issue.
Thanks.

**Comment by Termplexed** [comment]
Thanks. Install works fine and all running smooth. Great work :1st_place_medal: 

Only noticed a small thing: 

On install the `imgs` folder is created with *user:group* as `www-data:nogroup` and permissions `0774`

When service starts this is changed to `nobody:nogroup` and permissions `0755` as per:

https://github.com/mikaku/Monitorix/blob/0ed93455e243fd15ec03010084b22dac32435055/monitorix#L740

Likely not an issue, but noticed.

**Comment by mikaku** [comment]
Yes, the issue about what ownership and permissions must go to the `imgs/` directory is always a problem because the user/group under what Monitorix HTTP built-in runs is always different than the user/group under what a third-party web server (Apache?) always run.

To make life easier to Debian users, we (@IzzySoft and me) agreed to set the permissions during the installation as `www-data:nogroup 0775` to make sure that both Apache and Monitorix will have group write permissions in `imgs/`.

Finally, Monitorix will set the user/group permissions on that directory according its configuration in the `<httpd_builtin>` section of the configuration file.

The permissions `0774` is probably a (harmless) typo, it should be `0775`.

**Comment by IzzySoft** [comment]
@mikaku Monitorix shouldn't change ownership, though – that's why we decided for 0774. If Monitorix changes it the way described, Apache will fail if the user decides to switch later.

* Owner `www-data` for Apache, so the first `7` ensures Apache can write
* Group `nogroup` for Monitorix, again with `7` to give full access
* World may see the directory but not what's inside, hence the `4` (security measure)

What your changing permissions accomplishes is:

* Apache loses its privileges and gets demoted to "world" with r/x but no longer can write (`5`)
* Nothing changes for Monitorix itself
* World now can read and execute (i.e. "look inside" but not change stuff, again `5`)

We can discuss whether Monitorix should be owner or group member. But all it should do is to check if it can read/write fine – and if it can, not change things around.

Well, my 2 ct, YMMV :wink:

**Comment by mikaku** [comment]
> that's why we decided for 0774.

I have 0775 in my emails (double checked). Anyway that's not the important part. I think that 0774 or even 0770 the result would be the same for a directory.

> But all it should do is to check if it can read/write fine – and if it can, not change things around.

Definitely this is the way to go. I like it.
Thanks Izzy!

**Comment by IzzySoft** [comment]
Gladly! Btw, I often use things like `is_readable()` or `is_writeable()` and in case of "no" spit out an understandable error. Could be done here as well, as fixing would be as easy as running `chmod` (maybe `chown` too, but that would be distribution-specific edge cases).
