### ISSUE TITLE
Is it possible to change the www folder to /dev/shm/monitorix/www

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#332]
To reduce write load I would like to place the `www` to /dev/shm/monitorix/www via `base_dir`. But monitorix doesn't accept this change because at boot it is empty. I could fill it myself but it would be nice if monitorix would just create this folder on demand if needed and fill it with the stuff (pngs, ...) it needs in it as this folder is anyhow just temporary content besides some pngs? Or be able to just move the `imgs` folder?

**Comment by bachandi** [comment]
It seems the missing directory is not the issue but the missing content in the directory. To my understanding you don't specify the `www` directory location by setting `base_dir` but you point monitorix to the content it needs (cgi/monitorix.cgi) and in addition the generated images will be created there. Is this indented?
I think it would be nice if one could specify the `imgs` or even `www` folder directory in the config file seperatly to the location of `monitorix.cgi` as they are always generated on demand. Or is this already possible or not desired?

**Comment by mikaku** [comment]
The contents of the `www` directory contains files (and directories) that came as part of the installation, that is, they are not created when Monitorix is started. These files and directories are mostly for read only.

Since the only reason why you are wanting this is to safe disk life by avoiding the constant creation of image files, I recommend you to just symlink that directory to anywhere in `/dev/shm` (as you originally suggested).

**Comment by bachandi** [comment]
Yes. I ended up creating a tmpfs ramdisk on boot with mountpoint in `/var/lib/monitorix/www/imgs`. Probably the easiest way to use it this way.

**Comment by mikaku** [comment]
OK.

Perhaps a new pair configure options to execute a remote script during Monitorix start-up and when Monitorix is shut down would help you to setup this.

Just let me know.
