### ISSUE TITLE
Don't reset disks stats when adding a new line in <fs><list>

### ISSUE THREAD

**Issue by Ealrann** [mikaku/Monitorix#339]
Hello,

First thank you for this tool, it's overwhelmingly useful :+1: 

On some servers, I regularly remove/add hdds, so I update the monitorix configuration to see them. Since I have a lot of disks (JBOD), I define them over multiple lines: 
```
<fs>
        <list>
                0 = /, swap, /home
                1 = /mnt/vol1, /mnt/vol2, /mnt/vol3, /mnt/vol4, /mnt/vol5, /mnt/vol6, /mnt/vol7, /mnt/vol8
                2 = /mnt/vol9, /mnt/vol10, /mnt/vol11, /mnt/vol12, /mnt/vol13, /mnt/vol14, /mnt/vol15, /mnt/vol16
                3 = /mnt/vol17, /mnt/vol18, /mnt/vol19, /mnt/vol20, /mnt/vol21, /mnt/vol22, /mnt/vol23, /mnt/vol24
                4 = /mnt/vol25, /mnt/vol26, /mnt/vol27, /mnt/vol28, /mnt/vol29, /mnt/vol30, /mnt/vol31, /mnt/vol32
                5 = /mnt/vol33 ,/mnt/vol34, /mnt/vol35, /mnt/vol36
        </list>
```

But, I remarked that when I add a new line in this list, all the previous recorded data are lost. I'd like to keep them to have long term statistics.

Is there a way to avoid loosing data ?

**Comment by mikaku** [comment]
> First thank you for this tool, it's overwhelmingly useful +1

I'm glad to know you are enjoying Monitorix.

> Is there a way to avoid loosing data ?

As stated in `monitorix.conf(5)` man page:

```
WARNING: Every time the number of groups in this option changes, Monitorix will resize the fs.rrd file accordingly, removing all historical data.
```

All `.rrd` are fixed-size files based on an immutable internal structure (re)generated when you (re)define the settings in the configuration file. Due to this nature it's not possible to include new values without changing its internal structure.

AFAIK, RRDtool does not provide an automatic mechanism to add/delete values on an `.rrd` file and keep the historical data intact. The only way to do this process is manually and it is largely tedious.

I understand your problem, and it also happened to me. The quick work-around is to *reserve* as much as groups to avoid having to extend the file some time in the future.

Something like this:

```
<fs>
        <list>
                0 = /, swap, /home
                1 = /mnt/vol1, /mnt/vol2, /mnt/vol3, /mnt/vol4, /mnt/vol5, /mnt/vol6, /mnt/vol7, /mnt/vol8
                2 = /mnt/vol9, /mnt/vol10, /mnt/vol11, /mnt/vol12, /mnt/vol13, /mnt/vol14, /mnt/vol15, /mnt/vol16
                3 = /mnt/vol17, /mnt/vol18, /mnt/vol19, /mnt/vol20, /mnt/vol21, /mnt/vol22, /mnt/vol23, /mnt/vol24
                4 = /mnt/vol25, /mnt/vol26, /mnt/vol27, /mnt/vol28, /mnt/vol29, /mnt/vol30, /mnt/vol31, /mnt/vol32
                5 = /mnt/vol33 ,/mnt/vol34, /mnt/vol35, /mnt/vol36
                6 =
                7 =
                8 =
                9 =
        </list>
```

**Comment by Ealrann** [comment]
Thanks for the info, it definitely solve my use case ! :tada:
