### ISSUE TITLE
Poor temporal resolution suddenly (DST issue?)

### ISSUE THREAD

**Issue by WildPenquin** [mikaku/Monitorix#460]
Hi,

I noticed today that my graphs have a very poor temporal resolution. This is most apparent in daily graphs, but can be seen in weekly and monthly graphs, too. I have the issue on two separate hosts.  This was definitely not how it used to be!

An example:
![kuva](https://github.com/mikaku/Monitorix/assets/3398736/ab9980ca-6b39-4c1c-8412-cad229673e85)

My guess is that DST (daylight saving time) may have something to do with this. The time was moved backwards 1h last night in my timezone (EEST->EET) =)

If it's the DST then this issue manifests itself only twice per year and only in some parts of the world.

Cheers!

**Comment by mikaku** [comment]
Yes, it was already commented in #361 and #292.

This is apparently caused because today is a 25-hour day, which makes a totally different, and not supported, time frame. Tomorrow everything will be fine again.

Indeed, it can also appear during this week and even during the whole month, depending of the type of the graph.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.

**Comment by WildPenquin** [comment]
Yeah I think it can be left as closed.

Howevere if I have time, I might take a look at this problem. I'm thinking about something like "fixing" the data to the specified size whenever a TZ change has been at the graph when a graph is drawn (to a temporary file) or something. I think I've looked at the code (a long time ago), it would be a bit hairy / messy / a bit of work. But after all, we do get a bit ugly / less informative weekly graphs at slightly less than 2% of the time (monthly graphs have so little temporal resolution to begin with, that it doesn't matter that much, but if one considers that, monthly graphs have the same problem ~8% of the time).

**Comment by mikaku** [comment]
Yes, I think it could be fixed by adding some more rows in the [RRAs](https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html) when defining the `.rrd`internal structure, but it's hard to test and I'm not sure if it worth the cost.

Perhaps even by the time we could implement a solution, they will abolish the Daylight Saving Time. :rofl:

**Comment by WildPenquin** [comment]
Yeah, I believe that would be the proper fix! ;-)

**Comment by IzzySoft** [comment]
> Perhaps even by the time we could implement a solution, they will abolish the Daylight Saving Time. 

If THAT's the outcome, I'd say it might be worth the efforts :see_no_evil:

**Comment by mikaku** [comment]
> If THAT's the outcome, I'd say it might be worth the efforts 🙈

Hahaha, yeah. This is crazy.
:smile:
