### ISSUE TITLE
MySQL stats broken in 3.5.1

### ISSUE THREAD

**Issue by skibbipl** [mikaku/Monitorix#47]
After upgrde to 3.5.1 MySQL stats stopped working:

```
Mon May 19 10:01:01 2014 - mysql::mysql_update: Cannot connect to MySQL '/var/run/mysqld/mysqld.sock'.
Mon May 19 10:01:01 2014 - ERROR: while updating /var/lib/monitorix/mysql.rrd: /var/lib/monitorix/mysql.rrd: expected timestamp not found in data source from N
```

MySQL listens on socket - tested with socat.

**Comment by mqudsi** [comment]
I was bit by this today, thanks to @skibbipl comment, I figured it out quickly. If monitorix complained about duplicate definitions, that might have helped avoid the confusion as I defined my own MySQL configuration in /etc/monitorix/monitorix.conf which conflicted with the incorrect (package-default) one.

**Comment by mikaku** [comment]
Hi mqudsi,

If Monitorix advises with a message of every duplicated definition in both configuration files then it would be a complete mess on every start up, since the reason of the extra configuration is precisely to change default values with new ones. Such mess would create the contrary effect to alert the user because that excessive verbosity might make reduce the interest of the log file.

I think that showing the current message of loading an extra configuration file is enough to give you a clue of what might be happening.

Thanks.

**Comment by seefood** [comment]
Also, if I may suggest, document the commandline for a socket config. the man says each DESC line gets three parameters, that makes sense for a TCP connection but not for a socket file. I understand the "3306" is a filler value I can ignore?

**Comment by mikaku** [comment]
You're right, let me know if that suffices. :)
Thanks!
