### ISSUE TITLE
HTML templates for initial page and graphs page

### ISSUE THREAD

**Issue by lorenzos** [mikaku/Monitorix#53]
What about using HTML templates to generate the Monitorix initial page (the one with the host/graph/time form) and the graphs page?

I wanted to customize the styling a bit (table thick borders, big fonts, etc), but I noticed all HTML generation is hard-coded in Perl scripts. Unfortunately I'm a PHP developer, and I know nothing about Perl. If I was, not only I had modified my pages, but also helped developing a template system here.

**Comment by JaimeObregon** [comment]
+1. This reminded me of a HTML5 Bootstrap based theme I made for a different charting script. It has nothing to do with Monitorix, on at the end it's basically the same: an eye-candy wrapper for RRD charts: https://mailstats.iteisa.com

HTH. As @lorenzos, I'm fluent on frontend dev, but illiterate on Perl...

**Comment by JaimeObregon** [comment]
I've made some progress on this and came up with a modern HTML5 template based on Bootstrap, jQuery and some JavaScript. This template is easy to extend, customize and translate (it's written in English), but it will require some work in Monitorix to decouple the current embedded HTML markup from the Perl files, as @lorencos initially suggested.

![screenshot](https://cloud.githubusercontent.com/assets/417226/9500998/e0944134-4c28-11e5-9a0a-9629bf9f3c0f.png)

(The screenshot is from a larger add-on I've built, see https://github.com/JaimeObregon/monitorix-board

**Comment by mikaku** [comment]
@JaimeObregon,

Thanks for your ideas, they are very valuable and welcome.

I think that we should keep the current Monitorix view since it's pretty lightweight and it's perfect for people that don't want full bloated web interfaces. Instead, we should let the user choose the Monitorix web interface by setting a new option in the configuration file. Something like `user_interface = classic` or `user_interface = modern`.

The screen shot you posted looks like a more Multihost related substitute than a substitute for the main Monitorix interface. Well, I guess this is something you have in a very early stage.

Just let me know your progress on this.
Thanks

**Comment by gonace** [comment]
So how is this going? I've seen no template functionallity added to Monitorix, and it's been years since this matter where discussed?

I'm interested in building the template system for Monitorix but if my work never is merged into Monitorix then well...it's just a waste of time?

**Comment by ameiji** [comment]
@gonace Until then you may look onto collectd + grafana combo ;)

**Comment by mikaku** [comment]
@gonace, it looks like people come here with a lot of energy and ideas, ... but then such energy vanishes for any reason (jobs, family, time, no interest, etc.)

I'm interested to include a template to be able to choose between the current *classic* and something different created by someone. Until now, no one has showed me nothing that can be accomplished in this manner.

**Comment by mikaku** [comment]
CSS has been introduced in the main page in #298 
More to come ...
