### ISSUE TITLE
Add custom url config value to allow reverse proxy to work

### ISSUE THREAD

**Issue by milouse** [mikaku/Monitorix#58]
Hi!

In my infrastructure, I use hiawatha webserver. An easy way to open monitorix to the wild internet is to use the reverse proxy possibility of hiawatha. This way, I just have to configure monitorix to listen to localhost connection through its builtin http server. It seems to works out of the box, but.... No graphs are displayed (all images are broken). This comes from the fact you force `$config{url}` to be a combination of hostname and port config value.

I suggest to do the following modification to allow a new `url` config value, which will take precedence over the hostname/port default if present.

``` diff
--- /srv/http/monitorix/cgi/monitorix.cgi   2014-08-09 18:13:34.000000000 +0200
+++ monitorix.cgi   2014-08-10 13:16:39.252252098 +0200
@@ -257,11 +257,13 @@
    }
 }

-$config{url} = ($ENV{HTTPS} || ($config{httpd_builtin}->{https_url} || "n") eq "y") ? "https://" . $ENV{HTTP_HOST} : "http://" . $ENV{HTTP_HOST};
-$config{hostname} = $config{hostname} || $ENV{SERVER_NAME};
-if(!($config{hostname})) { # called from the command line
-   $config{hostname} = "127.0.0.1";
-   $config{url} = "http://127.0.0.1";
+if(!$config{url}){
+   $config{url} = ($ENV{HTTPS} || ($config{httpd_builtin}->{https_url} || "n") eq "y") ? "https://" . $ENV{HTTP_HOST} : "http://" . $ENV{HTTP_HOST};
+   $config{hostname} = $config{hostname} || $ENV{SERVER_NAME};
+   if(!($config{hostname})) {  # called from the command line
+       $config{hostname} = "127.0.0.1";
+       $config{url} = "http://127.0.0.1";
+   }
 }
 $config{url} .= $config{base_url};
```

**Comment by IzzySoft** [comment]
I thought I was going crazy until finding this (already panicked I might have borked the Apache conf). So when running behind a reverse proxy, one has to decide for a protocol? No more chance to access the same installation via http *and* https (e.g. to have a fallback)?

**Comment by milouse** [comment]
I'm afraid you have to choose a protocole. By the way, you should configure apache to redirect permanently your clients from http to https and provide the https url in the url_prefix_proxy parameter. What kind of fallback you need ? Some firewall blocking your https connection?

**Comment by IzzySoft** [comment]
Thanks, @milouse (and yes, I'm aware of the redirect etc / HSTS). The machine I'm talking about is currently reachable from two sides: via a Squid proxy on one machine, and via an "Apache reverse proxy" on another. So what I've had in mind is to use one of the two by default, and have the other one in case the default is down – preferably via different host names (DNS). This part doesn't much affect the protocol, but rather the host name (while I'd need to fix the protocol as Squid uses plain http to access the backend, so I get "mixed content" otherwise).

Second part is like you said: If somehow https is unavailable (think of "self-signed certs" and a strict browser), I'd like to have the "plain http" available as fallback.

I know there's probably no way to have both paths available simultaneously (depending on where the request comes from – though in this case, I could see that a) by the remote/gateway/proxy IP and b) by the network interface of the incoming request): I can either fix the protocol or not, and fix the host-name or not. But currently, I've either to fix both or none – so splitting that would be fine.

For me, both things are of minor priority currently – but still I feel they should be considered (so a solution is available when needed). No pressure :)
