### ISSUE TITLE
Request : Generic feature for generic chart

### ISSUE THREAD

**Issue by Tarjaizaid** [mikaku/Monitorix#81]
Hello,

After the advanced iptable request, i've an another idea.

Could you add a feature for generate graph by getting a numeric value returned by a user script specified in monitorix option.

A first example concern teamspeack server. The community developed code to get number of client connected to the serveur (http://stackoverflow.com/questions/22738039/teamspeak-query-number-of-connected-clients).
This code will be edited to return only a numeric value

Example :
Mychart,/opt/script/mychart.sh

With this feature, we should be able to generate our personnal chart :) 
What is your opinion ?

Thanks

**Comment by mikaku** [comment]
Hello,

I think that Munin is a better solution for your purpose since it has developed from the idea of create third-party plugins in a relatively easy way.

On the other hand, if you want to create a Teamspeak graph for Monitorix, I recommend you to take an approximate existing module as base and develop your own on top of it.

Thanks.
