### ISSUE TITLE
process.pm: ps regex doesn't work intuitively for names with spaces

### ISSUE THREAD

**Issue by cwc** [mikaku/Monitorix#94]
With the [process parsing code in process.pm](https://github.com/mikaku/Monitorix/blob/69fc360dde9472923704a5432106f5103059a74a/lib/process.pm#L173-L184) in mind, given this ps output:

```
16777 Plex Media Serv ./Plex Media Server
```

The following is true:

`trim($2) == Plex`
`trim($3) == Media Serv ./Plex Media Server`

I'd offer a fix but my Perl-fu is weak. Maybe pass the ps output through `cut` somehow?

**Comment by mikaku** [comment]
Yeah ... I know, process names with spaces aren't supported. Well, from my point of view, people that name processes with spaces shouldn't exist in this planet either.

I like the way how currently is parsed because it's pretty strong to possible future changes in the columns width of the `ps` command. Substituting this by something that relies on a fixed column position wouldn't be a great idea.

So, why don't combine both approaches?

I'll work on it and I'll let you know as soon as I have something interesting.
Thanks.

**Comment by mikaku** [comment]
@cwc,

Just let me know if that patch works as you expected.
Thanks.

**Comment by uraymeiviar** [comment]
![screen shot 2015-06-28 at 6 46 09 am](https://cloud.githubusercontent.com/assets/4237078/8394425/7950496e-1d61-11e5-9f7a-828d35c4e1a0.png)

seems to work, thanks for patch

**Comment by mikaku** [comment]
@uraymeiviar,

Thanks for your testings.
I'll close that issue.
